#!/usr/bin/env php
<?php

require_once ('vendor/autoload.php');
$projectDir = __DIR__;

// Input validation
$day = $_SERVER['argv'][1] ?? '';
if (!is_numeric($day) || $day < 1 || $day > 25) {
    die("Pass a day argument between 1 and 25\n");
}
$dayNr = str_pad((int)$day, 2, '0', STR_PAD_LEFT);
$filename = "$projectDir/src/Solutions/Day$dayNr.php";
if (file_exists($filename)) {
    die("Solution class for day $dayNr already exists\n");
}

// Create class & input files
$template = file_get_contents("$projectDir/src/Common/Resources/solution-template.txt");
$fileContents = str_replace('{{day_nr}}', $dayNr, $template);
file_put_contents($filename, $fileContents);
$inputFile = "$projectDir/var/input/day$dayNr.txt";
file_put_contents($inputFile, '');
$inputTestFile = "$projectDir/var/input/day$dayNr-test.txt";
file_put_contents($inputTestFile, '');

// Open class & input files in PhpStorm
exec('open -na "PhpStorm.app" --args "' . $filename . '" "' . $inputFile . '" "' . $inputTestFile . '"');

echo "Done!\n";